# Generated by Django 5.2.17 on 2026-09-29 20:02

import django.core.validators
import django.db.models.deletion
import horilla.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('guideline', 'Guideline'), ('procedure', 'Procedure'), ('code_of_conduct', 'Code of Conduct'), ('benefits', 'Benefits & Perks'), ('other', 'Other')], default='policy', max_length=30, verbose_name='Category')),
                ('body', models.TextField(blank=True, verbose_name='Content')),
                ('document', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF Document')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are listed first.', verbose_name='Display Order')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished entries are visible only to handbook editors.', verbose_name='Published')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Handbook Document',
                'verbose_name_plural': 'Handbook Documents',
                'ordering': ['order', 'title'],
            },
        ),
    ]
