# Generated by Django 5.2.17 on 2026-09-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_policy_specific_employees_policy_department_and_more'),
        ('leave', '0008_leaverequest_leaverequest_dates_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='historicalleaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.employee', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request_approved', to='employee.employee', verbose_name='Approved By'),
        ),
    ]
