# Generated by Django 5.2.17 on 2026-09-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_probation_end_date_and_notifications'),
        ('leave', '0009_leaverequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_prorated',
            field=models.BooleanField(default=False, help_text='Allocate a pro-rated balance for the remaining months of the year when an employee completes probation or their contract becomes active. Requires a yearly reset.', verbose_name='Pro-rate on confirmation'),
        ),
        migrations.CreateModel(
            name='ProRataLeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_year', models.IntegerField(help_text='Calendar year the reset cycle ends in.')),
                ('effective_date', models.DateField()),
                ('allocated_days', models.FloatField(default=0)),
                ('source', models.CharField(choices=[('probation', 'Probation completed'), ('contract', 'Contract activated'), ('joining', 'Joining date')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorata_allocations', to='employee.employee')),
                ('leave_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Pro-rata Leave Allocation',
                'verbose_name_plural': 'Pro-rata Leave Allocations',
                'unique_together': {('employee_id', 'leave_type_id', 'cycle_year')},
            },
        ),
    ]
