# Generated by Django 5.2.17 on 2026-09-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_policy_specific_employees_policy_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Probation / Internship End Date'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Probation / Internship End Date'),
        ),
        migrations.CreateModel(
            name='ProbationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probation_end_date', models.DateField()),
                ('milestone', models.CharField(choices=[('t-10', '10 days before'), ('t-3', '3 days before'), ('t-0', 'On completion'), ('t+3', 'Overdue')], max_length=10)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_notifications', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Probation Notification',
                'verbose_name_plural': 'Probation Notifications',
                'unique_together': {('employee_id', 'probation_end_date', 'milestone')},
            },
        ),
    ]
